name: animate_map_markers
description: "Animation utilities for markers of the google_maps_flutter package."
version: 0.0.8
homepage: https://github.com/FlutterAppmakers/animate_map_markers
repository: https://github.com/FlutterAppmakers/animate_map_markers
issue_tracker: https://github.com/FlutterAppmakers/animate_map_markers/issues
screenshots:
  - description: animated markers with carousel slider
    path: gifs/animated-markers-carousel.gif
  - description: animated markers with elastic Effect cards
    path: gifs/animated-markers-elastic-carousel.gif
  - description: Animated markers
    path: gifs/animated-markers.gif
  - description: animated markers with draggable sheet
    path: gifs/animated-markers-sheet.gif
  - description:  animated markers using svg images
    path: gifs/animated-markers-svg.gif

topics:
  - google-maps
  - map
  - animation

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.12.3
  carousel_slider: ^5.0.0
  flutter_svg: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.6
  build_runner: ^2.0.4
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  #assets:

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
